{
 "title": "NEA_EHI_BEB_sensorpi",
 "description": "This dashboard monitors the sensor readings from HBK World's sensor",
 "tags": [ "raspberrypi-node-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info{job=\"integrations/raspberrypi-node\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=\"integrations/raspberrypi-node\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "LANXI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Liveliness",
   "type": "stat",
   "description": "PINGs the static IP of the lanxi module, if there's a reply return 1 if not 0",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lanxi_alive{device_id=\"lanxi-01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P-P",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "lanxi_amplitude_max{channel=\"1\"} - lanxi_amplitude_min{channel=\"1\"}",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "lanxi_amplitude_max{channel=\"2\"} - lanxi_amplitude_min{channel=\"2\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "FFT input (MA) - Channel 1",
   "type": "timeseries",
   "description": "Moving average 10 minutes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg_over_time(lanxi_amplitude_max{channel=\"1\"}[10m])",
     "legendFormat": "max: {{channel}}"
    },
    {
     "expr": " avg_over_time(lanxi_amplitude_min{channel=\"1\"}[10m])",
     "legendFormat": "min: {{channel}}"
    }
   ]
  },
  {
   "title": "FFT intput (MA) - Channel 2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "avg_over_time(lanxi_amplitude_max{channel=\"2\"}[10m])",
     "legendFormat": "max: {{channel}}"
    },
    {
     "expr": " avg_over_time(lanxi_amplitude_min{channel=\"2\"}[10m])",
     "legendFormat": "min: {{channel}}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest metrics received",
     "type": "stat",
     "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vector(1) and on() ((count(up{job=~\"$job\"} == 1) > 0) and (absent(absent(node_uname_info{job=~\"$job\"})))) or vector(0) and on() ((count(up{job=~\"$job\"}) > 0) and (absent(node_uname_info{job=~\"$job\"})))\n"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "stat",
     "description": "Shows if metrics are being received for the selected time range.",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vector(1) and on() ((count(up{job=~\"$job\"} == 1) > 0) and (absent(absent(node_uname_info{job=~\"$job\"})))) or vector(0) and on() ((count(up{job=~\"$job\"}) > 0) and (absent(node_uname_info{job=~\"$job\"})))\n"
      }
     ]
    },
    {
     "title": "Integration version",
     "type": "stat",
     "description": "Shows the installed version of this integration.",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {}
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "The duration of time that has passed since the last reboot or system start.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Hostname",
     "type": "stat",
     "description": "System's hostname.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 127 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_uname_info{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Kernel version",
     "type": "stat",
     "description": "Kernel version of linux host.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 127 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_uname_info{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "OS",
     "type": "stat",
     "description": "Operating system",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 127 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_os_info{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}\n"
      }
     ]
    },
    {
     "title": "CPU count",
     "type": "stat",
     "description": "CPU count is the number of processor cores or central processing units (CPUs) in a computer,\ndetermining its processing capability and ability to handle tasks concurrently.\n",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 145 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count without (cpu) (node_cpu_seconds_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})",
       "legendFormat": "Cores"
      }
     ]
    },
    {
     "title": "Memory total",
     "type": "stat",
     "description": "Amount of random-access memory (RAM) installed.\nIt represents the system's available working memory that applications and the operating system use to perform tasks.\nA higher memory total generally leads to better system performance and the ability to run more demanding applications and processes simultaneously.\n",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Memory total"
      }
     ]
    },
    {
     "title": "Total swap",
     "type": "stat",
     "description": "Total swap available.\n\nSwap is a space on a storage device (usually a dedicated swap partition or a swap file) \nused as virtual memory when the physical RAM (random-access memory) is fully utilized.\nSwap space helps prevent memory-related performance issues by temporarily transferring less-used data from RAM to disk,\nfreeing up physical memory for active processes and applications.\n",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Root mount size",
     "type": "stat",
     "description": "Total capacity on the primary mount point /.\n",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", mode=~\"idle|iowait|steal\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})\n) * 100\n",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "System load average over the previous 1, 5, and 15 minute ranges.\n\nA measurement of how many processes are waiting for CPU cycles. The maximum number is the number of CPU cores for the node.\n",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "- Used: The amount of physical memory currently in use by the system.\n- Cached: The amount of physical memory used for caching data from disk. The Linux kernel uses available memory to cache data that is read from or written to disk. This helps speed up disk access times.\n- Free: The amount of physical memory that is currently not in use.\n- Buffers: The amount of physical memory used for temporary storage of data being transferred between devices or applications.\n- Available: The amount of physical memory that is available for use by applications. This takes into account memory that is currently being used for caching but can be freed up if needed.\n",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_Cached_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}\n)\n",
     "legendFormat": "Memory used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory cached"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory available"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk reads/writes",
     "type": "timeseries",
     "description": "Disk read/writes in bytes per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
       "legendFormat": "{{ device }} read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
       "legendFormat": "{{ device }} written"
      },
      {
       "expr": "irate(node_disk_io_time_seconds_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
       "legendFormat": "{{ device }} io util"
      }
     ]
    },
    {
     "title": "Disk space usage",
     "type": "table",
     "description": "Disk utilisation in percent, by mountpoint. Some duplication can occur if the same filesystem is mounted in multiple locations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{fstype!=\"\", mountpoint!=\"\", job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}"
      },
      {
       "expr": "node_filesystem_avail_bytes{fstype!=\"\", mountpoint!=\"\", job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{ mountpoint }} free"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "timeseries",
     "description": "Network traffic (bits per sec) measures data transmitted and received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_receive_bytes_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__range]\n    ) > 0\n",
       "legendFormat": "{{ device }} received"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_transmit_bytes_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__range]\n    ) > 0\n",
       "legendFormat": "{{ device }} transmitted"
      }
     ]
    },
    {
     "title": "Network errors and dropped packets",
     "type": "timeseries",
     "description": "**Network errors**:\n\nNetwork errors refer to issues that occur during the transmission of data across a network. \n\nThese errors can result from various factors, including physical issues, jitter, collisions, noise and interference.\n\nMonitoring network errors is essential for diagnosing and resolving issues, as they can indicate problems with network hardware or environmental factors affecting network quality.\n\n**Dropped packets**:\n\nDropped packets occur when data packets traveling through a network are intentionally discarded or lost due to congestion, resource limitations, or network configuration issues. \n\nCommon causes include network congestion, buffer overflows, QoS settings, and network errors, as corrupted or incomplete packets may be discarded by receiving devices.\n\nDropped packets can impact network performance and lead to issues such as degraded voice or video quality in real-time applications.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_errs_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
       "legendFormat": "{{ device }} errors transmitted"
      },
      {
       "expr": "irate(node_network_receive_errs_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
       "legendFormat": "{{ device }} errors received"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
       "legendFormat": "{{ device }} transmitted dropped"
      },
      {
       "expr": "irate(node_network_receive_drop_total{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
       "legendFormat": "{{ device }} received dropped"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "description": "Temperature sensors values.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{job=\"integrations/raspberrypi-node\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{chip}}/{{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}