apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: superset
    server: https://kubernetes.default.svc
  project: data
  source:
    repoURL: http://apache.github.io/superset/
    targetRevision: 0.13.4
    chart: superset
    helm:
      releaseName: superset
      valuesObject:
        bootstrapScript: |
          #!/bin/bash
          pip install \
            "psycopg2-binary>=2.9.10" pillow \
            &&\
          if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
        service:
          type: ClusterIP
          port: 80
        supersetNode:
          extraContainers:
            - name: tailscale-sidecar
              image: ghcr.io/tailscale/tailscale:latest
              env:
                - name: TS_KUBE_SECRET
                  value: tailscale-auth
                - name: TS_AUTHKEY
                  valueFrom:
                    secretKeyRef:
                      name: tailscale-auth
                      key: TS_AUTHKEY
                - name: TS_USERSPACE
                  value: "false"
              securityContext:
                capabilities:
                   add:
                    - NET_ADMIN
        extraSecretEnv:
          SUPERSET_SECRET_KEY: <REDACTED>
        configOverrides:
          my_overrides: |
            ENABLE_PROXY_FIX = True
            FEATURE_FLAGS = {
             'ENABLE_TEMPLATE_PROCESSING': True
            }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
