apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: data
  source:
    repoURL: http://airflow.apache.org/
    targetRevision: 1.15.0
    chart: airflow
    helm:
      releaseName: airflow
      valuesObject:
        images:
          migrationsWaitTimeout: 600
          useDefaultImageForMigration: true
        webserver:
            extraContainers:
              - name: tailscale-sidecar
                image: ghcr.io/tailscale/tailscale:latest
                env:
                  - name: TS_KUBE_SECRET
                    value: tailscale-auth
                  - name: TS_AUTHKEY
                    valueFrom:
                      secretKeyRef:
                        name: tailscale-auth
                        key: TS_AUTHKEY
                  - name: TS_USERSPACE
                    value: "false"
        statsd:
          enabled: false
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
