apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: data
  source:
    repoURL: http://airflow.apache.org/
    targetRevision: 1.15.0
    chart: airflow
    helm:
      releaseName: airflow
      valuesObject:
        webserverSecretKeySecretName: webserver-secret-key
        fernetSecretKeyName: airflow-fernet-key
        images:
          migrationsWaitTimeout: 600
          useDefaultImageForMigration: true
        webserver:
          service:
            annotations:
              tailscale.com/expose: "true"
          webserverConfig: |
              CSRF_ENABLED = False
        statsd:
          enabled: false
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync
          useHelmHooks: false
          applyCustomEnv: false
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/NEA-EHI-Informatics/airflow
            branch: production
            credentialsSecret: git-credentials
            subPath: dags
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
