apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
stringData:
  TS_AUTHKEY: <REDACTED>
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
stringData:
  fernet-key: <REDACTED>
---
apiVersion: v1
kind: Secret
metadata:
  name: webserver-secret-key
stringData:
  webserver-secret-key: <REDACTED>